// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6MqShBos-jfReBTht72vBRUHMYDZhAG4',
    appId: '1:844415929382:android:7c82ae7ee47f19aebaeae7',
    messagingSenderId: '844415929382',
    projectId: 'mandalart-project',
    storageBucket: 'mandalart-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy45yaRkOcl5NN5BcW20jjyMhiUVDre_o',
    appId: '1:844415929382:ios:ca434022e84a6ad4baeae7',
    messagingSenderId: '844415929382',
    projectId: 'mandalart-project',
    storageBucket: 'mandalart-project.appspot.com',
    androidClientId: '844415929382-jd0k1br74lseatg8hdfflfe45g4h9k5n.apps.googleusercontent.com',
    iosClientId: '844415929382-pfhbmttt83h0ujjdab8ba1g33rol1d2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mandalart',
  );
}
